# Generated by Django 4.0.2 on 2022-07-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('year_born', models.IntegerField(null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('country_born', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='lmdbapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=10)),
                ('imdb_rating', models.FloatField(null=True)),
                ('imdb_amount_ratings', models.IntegerField()),
                ('work_type', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('length', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('cast', models.ManyToManyField(related_name='starred_in', to='lmdbapp.Person')),
                ('countries', models.ManyToManyField(to='lmdbapp.Country')),
                ('directors', models.ManyToManyField(related_name='directed_works', to='lmdbapp.Person')),
                ('genres', models.ManyToManyField(to='lmdbapp.Genre')),
                ('languages', models.ManyToManyField(to='lmdbapp.Language')),
                ('writers', models.ManyToManyField(related_name='written_works', to='lmdbapp.Person')),
            ],
        ),
    ]
